#!/bin/bash

#digitalocean's token
DIGITALOCEAN_TOKEN=""
readonly DIGITALOCEAN_TOKEN
#vultr's api key
VULTR_APIKEY=""
readonly VULTR_APIKEY
#domain
DOMAIN="redteam.fun"
readonly DOMAIN
#namesilo's key
NAMESILO_KEY=""
readonly NAMESILO_KEY
#DataBase file 
DataBase="./data/DataBase"
readonly DataBase